name: Terraform ECR
on:
  push:
    branches:
      - main

jobs:
  create_ecr_repository:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY_NAME: my-repo1
      DOCKERFILE_PATH: ./Dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.4.0"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Navigate to Terraform directory
        run: cd terraform && terraform init && terraform plan
      - name: Apply Terraform
        run: cd terraform && terraform apply -auto-approve
      - name: Login to Amazon ECR
        id: login-ecr
        run: echo $(aws ecr get-login-password --region ${{ env.AWS_REGION }} ) | docker login -u AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      - name: Build Docker image
        run: docker build -t "my-iamage" .
      - name: Tag image
        run: docker tag "my-iamage" ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY_NAME }}
      - name: Push image to Amazon ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY_NAME }}
